### ISSUE TITLE
Integration with PiHole

### ISSUE THREAD

**Issue by james-gonzalez** [ar51an/unbound-redis#3]
Hey,

First of all, wanted to say, really love the idea of the project, the code looks great and the instructions are incredibly detailed, which I appreciate. 

Just one question, I already run Pi-Hole with Unbound. Would I get any benefit in replacing the Unbound part with this one?

Thanks!

**Comment by ar51an** [comment]
Hello,
Thank you.

1 - You will be able to use the latest unbound 1.17.1. Bullseye distribution has 1.13.1 version unbound. Unbound 1.17.1 has many bugs fixed and it has better performance.
2 - If you use redis along with it. You will get persistent cache (machine reboot/unbound restart)
3 - In case of multiple instances of Unbound in local network, redis gives the ability of shared cache across multiple instances.

Check this comment under my reddit post:
https://www.reddit.com/r/selfhosted/comments/119l044/comment/jaoe7kn/?utm_source=share&utm_medium=web2x&context=3

Edit:
It does recursive resolving from the root servers rather than forwarding to other upstream dns servers. So it will act as your true dns server.
Lastly if you are already using pi-hole for ad-blocking comment out the blocklist "include:" at the top in "unbound.conf"

**Comment by james-gonzalez** [comment]
Thanks!
