### ISSUE TITLE
unixsocket wrong permissions

### ISSUE THREAD

**Issue by whyisthisbroken** [ar51an/unbound-redis#8]
unixsocket should be "unixsocketperm 770"

with 707 unbound wont start 

https://github.com/ar51an/unbound-redis?tab=readme-ov-file#-%E2%84%B9%EF%B8%8F-tips--notes

**Comment by ar51an** [comment]
Paste the unbound log error with 707 redis socket permission.
Also paste the output of below cmds:
`id unbound`
`id redis`
`ls -l /var/run/redis`

707 mean owner (redis user) can read/write/execute and every other user (including unbound user) can read/write/execute

770 mean redis user can read/write/execute and any other user within redis group can read/write/execute

707 is very lenient option. You must have done something wrong somewhere else. Unbound log error can be helpful. So it is the other way around. With "unixsocketperm 770", you must add unbound user to redis group otherwise it won't work. I mentioned that under "Note:" section in the Readme.
